# action.yml
name: 'Current Branch'
description: 'Grab the current branch and/or tag of your repo 👍'
branding:
    icon: 'git-branch'
    color: 'black'
outputs:
  branch:
    description: 'Current branch name'
  tag:
    description: 'Corresponding branch tag'
runs:
  using: 'docker'
  image: 'Dockerfile'