on: [push]

jobs:
  current-branch-job:
    runs-on: ubuntu-latest
    name: Test action
    steps:
    - name: Use action
      id: get-branch
      uses: ryolambert/current-branch@v1.0
    - name: Echo outputs
      run: echo "name=${{ steps.get-branch.outputs.branch }} - tag=${{ steps.get-branch.outputs.tag }}"
